# Generated by Django 2.0 on 2017-12-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='站长姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('city', models.CharField(max_length=32, verbose_name='所在城市')),
                ('introduction', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('read_count', models.IntegerField(verbose_name='阅读数')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=204800)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_category_title', models.CharField(max_length=32, verbose_name='所属文章分类')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=1024, verbose_name='网站介绍')),
                ('access_count', models.IntegerField(verbose_name='访问数量')),
            ],
        ),
        migrations.CreateModel(
            name='SiteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_category_title', models.CharField(max_length=32, verbose_name='所属站点分类')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=32, verbose_name='标签标题')),
            ],
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='site_category',
            field=models.ForeignKey(on_delete=True, to='blog.SiteCategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(on_delete=True, to='blog.ArticleCategory', verbose_name='文章分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='文章标签'),
        ),
    ]
